# .github/workflows/deploy.yml
name: Laravel CI + Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar chave SSH
      shell: bash
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        # Correção crítica: permissões mais restritas
        umask 077
        echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 3.138.174.128 >> ~/.ssh/known_hosts
        # Verificação das permissões
        ls -la ~/.ssh

    - name: Instalar Docker e deploy
      run: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@3.138.174.128 << 'EOF'
              # Atualizar pacotes (opcional)
              sudo apt-get update -qq

              # Instalar Docker se não existir
              if ! command -v docker &> /dev/null; then
                sudo apt-get install -y docker.io docker-compose
                sudo usermod -aG docker ubuntu
              fi

              # Reiniciar se necessário (após instalação do Docker)
              if [ -f /var/run/reboot-required ]; then
                sudo reboot
                sleep 60  # Esperar o reboot
              fi

              # Deploy da aplicação
              cd laravel-api
              docker compose down
              docker compose up -d --build
            EOF
