# .github/workflows/deploy.yml
name: Laravel CI + Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar chave SSH
          shell: bash
          env:
            EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          run: |
            mkdir -p ~/.ssh
            echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
            chmod 700 ~/.ssh
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Enviar projeto para EC2
      run: |
        rsync -avz --delete ./ ubuntu@3.138.174.128:/home/ubuntu/laravel-api

    - name: Executar comandos no servidor remoto
      run: |
        ssh ubuntu@3.138.174.128 << 'EOF'
          cd laravel-api
          docker compose down
          docker compose up -d --build
        EOF
