# .github/workflows/deploy.yml
name: Laravel CI + Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar chave SSH
      shell: bash
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        umask 077
        echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 3.138.174.128 >> ~/.ssh/known_hosts
        ls -la ~/.ssh

    - name: Criar diretório remoto (caso não exista)
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.138.174.128 "mkdir -p /home/ubuntu/laravel-api"

    - name: Enviar projeto para EC2 via rsync
      run: |
        rsync -av --delete -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./ ubuntu@3.138.174.128:/home/ubuntu/laravel-api

    - name: Instalar Docker e rodar Docker Compose
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.138.174.128 << 'EOF'
          # Atualizar pacotes
          sudo apt-get update -qq

          # Instalar Docker + Compose (se necessário)
          if ! command -v docker &> /dev/null; then
            sudo apt-get install -y docker.io docker-compose
            sudo usermod -aG docker ubuntu
          fi

          # Criar rede se precisar (opcional)
          sudo docker network inspect laravel-net >/dev/null 2>&1 || \
            sudo docker network create laravel-net

          # Subir app
          cd /home/ubuntu/laravel-api
          docker-compose down
          docker-compose up -d --build
        EOF
